import { Customer } from "../models/Customer";
export const customers: Customer[] = [
    {
        customer_id: "CUST001",
        name: "Nguyen Van A",
        phone_number: "+84901111222",
        country_code: "VN",
        address: "123 Le Loi, Hanoi",
        tax_id: "TX123456",
        timezone: "UTC+7",
    },
    {
        customer_id: "CUST002",
        name: "Le Thi B",
        phone_number: "+84902223333",
        country_code: "VN",
        address: "456 Ba Trieu, Hanoi",
        tax_id: "TX654321",
        timezone: "UTC+7",
    },
    {
        customer_id: "CUST003",
        name: "John Doe",
        phone_number: "+12025551234",
        country_code: "US",
        address: "789 Market St, San Francisco",
        tax_id: "TX998877",
        timezone: "UTC-8",
    },
    {
        customer_id: "CUST004",
        name: "Maria Gomez",
        phone_number: "+34910123456",
        country_code: "ES",
        address: "Plaza Mayor, Madrid",
        tax_id: "TX112233",
        timezone: "UTC+1",
    },
    {
        customer_id: "CUST005",
        name: "Pierre Dupont",
        phone_number: "+33612345678",
        country_code: "FR",
        address: "42 Rue de Paris, Paris",
        tax_id: "TX443322",
        timezone: "UTC+1",
    },
    {
        customer_id: "CUST006",
        name: "Chen Wei",
        phone_number: "+8613912345678",
        country_code: "CN",
        address: "No. 123 Beijing Road, Beijing",
        tax_id: "TX556677",
        timezone: "UTC+8",
    },
    {
        customer_id: "CUST007",
        name: "Kumar Reddy",
        phone_number: "+919876543210",
        country_code: "IN",
        address: "Block A, Mumbai",
        tax_id: "TX789456",
        timezone: "UTC+5:30",
    },
    {
        customer_id: "CUST008",
        name: "Olga Ivanova",
        phone_number: "+74951234567",
        country_code: "RU",
        address: "Lenin Street, Moscow",
        tax_id: "TX223344",
        timezone: "UTC+3",
    },
    {
        customer_id: "CUST009",
        name: "James Smith",
        phone_number: "+16175551234",
        country_code: "US",
        address: "1234 Elm St, New York",
        tax_id: "TX556699",
        timezone: "UTC-5",
    },
    {
        customer_id: "CUST010",
        name: "Liu Min",
        phone_number: "+8613123456789",
        country_code: "CN",
        address: "No. 456 Shanghai Road, Shanghai",
        tax_id: "TX223355",
        timezone: "UTC+8",
    },
];
